---
title: "Plotscaper demo"
author: "Adam Bartonicek"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, out.width="100%"}

library(plotscaper)

ps_scene(mtcars) |>
  ps_scatter(ps_map("wt", "mpg")) |>
  ps_bar(ps_map("cyl"))

```

```{r, out.width="100%", out.height="800px"}

layout1 <- matrix(c(1, 1, 2,
                 1, 1, 3, 
                 4, 4, 5), nrow = 3, byrow = TRUE)

ps_scene(mtcars, layout = layout1) |>
  ps_scatter(ps_map("wt", "mpg")) |>
  ps_square(ps_map("gear", "am")) |>
  ps_bar(ps_map("cyl")) |>
  ps_histo(ps_map("disp")) |>
  ps_bubble(ps_map("carb", "vs"))

```

```{r, out.width="100%", out.height="800px"}


diamonds <- ggplot2::diamonds
layout3 <- matrix(c(1, 1, 
                    2, 3), ncol = 2, byrow = TRUE)
data3 <- diamonds[sample(nrow(diamonds), 1e4, replace = FALSE), ]

ps_scene(data3, layout = layout3) |>
  ps_scatter(ps_map("carat", "price")) |>
  ps_histo(ps_map("table")) |>
  ps_square(ps_map("color", "clarity"))

```
